### ISSUE TITLE
NuGet reference to System.Net.Http causes telemetry to fail in default project template

### ISSUE THREAD

**Issue by Eilon** [aspnet/Microsoft.AspNet.TelemetryCorrelation#44] opened 2018-10-24 16:38 UTC
_From @GSPP on Wednesday, 24 October 2018 07:42:17_

On .NET 4.7.2, VS 15.8.7, Windows 7 there exists an issue which prevents a simple application from running:

1. Create new MVC web app.
2. Add library project and reference it.
3. Add System.Net.Http NuGet package to both projects.
4. Update all NuGet packages.

That's the entire setup. Now press F5. The application fails with this error:

```
Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

[FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.]
   Microsoft.AspNet.TelemetryCorrelation.ActivityExtensions.Extract(Activity activity, NameValueCollection requestHeaders) +0
   Microsoft.AspNet.TelemetryCorrelation.ActivityHelper.CreateRootActivity(HttpContext context) +156
   Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.Application_BeginRequest(Object sender, EventArgs e) +93
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +200
   System.Web.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0() +24
   System.Web.StepInvoker.Invoke(Action executionStep) +100
   System.Web.<>c__DisplayClass4_0.<Invoke>b__0() +17
   Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.OnExecuteRequestStep(HttpContextBase context, Action step) +64
   System.Web.<>c__DisplayClass284_0.<OnExecuteRequestStep>b__0(Action nextStepAction) +55
   System.Web.StepInvoker.Invoke(Action executionStep) +84
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +100
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +73
```

Note that due to this [related bug](https://github.com/dotnet/standard/issues/936) you might need to delete all bin/obj folders to be able to see this bug and not the other bug.

_Copied from original issue: aspnet/Mvc#8637_

**Comment by SergeyKanzhelev** [comment] 2018-10-24 18:17
yes, this reference bothers me as well. We only use a single method to parse a header and probably can just re-implement this parsing.

**Comment by GSPP** [comment] 2018-10-25 09:05
Why did this fail in the first place? Shouldn't adding this System.Net.Http package redundantly just work? After all I updated all NuGet packages to the latest version and supposedly the tooling inserted the correct binding redirects.

**Comment by SergeyKanzhelev** [comment] 2018-10-25 16:41
@GSPP I cannot repo - I tried different combination of netstandard or classic libraries.       

THis is what was added to `web.config`:

``` xml
<dependentAssembly>
  <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
</dependentAssembly>
```

You can try to troubleshoot [using `fuslog`](https://docs.microsoft.com/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer). I'd be interested what is the root cause in your case.

Also it's not clear for me why you need to add `System.Net.Http` as a NuGet package, not just use built-in one from GAC.

In any case it is safer for us to eliminate this dependency in TelemetryCorrelation module.

**Comment by lmolkova** [comment] 2019-08-20 02:35
the reference was removed, in #45. Closing this.

**Closed by lmolkova** 2019-08-20 02:35 UTC
Labels: bug
